
name: Run News Scraper (Google & Yahoo)

on:
  schedule:
    # ✅ JSTで毎時0分（1時間おき）
    - cron: '0 * * * *'
    # ✅ JSTで毎日15:00（→UTCでは06:00）
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      # GCPのSecretは不要になったため削除
      run: |
        python main.py

    - name: Commit and push if changed
      run: |
        # Gitのユーザー情報を設定
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # news_articles.xlsxファイルに変更があるか確認し、あればコミット＆プッシュ
        # `|| exit 0` は変更がない場合にエラーで終了させないためのおまじない
        git add news_articles.xlsx || exit 0
        git commit -m "Update news articles" || exit 0
        git push
        
    - name: Check for workflow failure (optional)
      if: ${{ failure() }}
      run: echo "Workflow failed. Check logs for details."
