name: Run Yahoo News Scraper and Commit Excel

on:
  schedule:
    # JSTで毎時0分（1時間おき）
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    # ワークフローにリポジトリへの書き込み権限を付与
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scraper
      run: |
        python main.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add yahoo_news_articles.xlsx
        # 変更があった場合のみコミットする
        if ! git diff-index --quiet HEAD; then
          git commit -m "Update Yahoo news articles"
          git push
        else
          echo "No changes to commit."
        fi
